name: Bump version and release
on:
  push:
    branches:
      - master
jobs:
  tag:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        WITH_V: true
        DEFAULT_BUMP: patch
        DRY_RUN: true
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${new_tag}
        release_name: Release ${new_tag}
        body: $(git log ${new_tag}..HEAD --oneline | grep "#patch\|#minor\|#major")
        draft: false
        prerelease: false
