name: Create release
on:
  push:
    branches:
      - master
jobs:
  tag:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true
      - run: echo "::set-output name=release_body::$(git log ${{steps.bump_version.outputs.new_tag}}..HEAD --oneline | grep '#patch\|#minor\|#major')"
        id: get_release_body
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{steps.bump_version.outputs.new_tag}}
          release_name: Release ${{steps.bump_version.outputs.new_tag}}
          body: ${{steps.get_release_body.outputs.release_body}}
          draft: false
          prerelease: false
